// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Form struct {
	ID   string `json:"id"`
	Blob string `json:"blob"`
}

type Health struct {
	Healthy bool   `json:"healthy"`
	Time    string `json:"time"`
	Version string `json:"version"`
}

type Mutation struct {
}

type Passage struct {
	Greek        string   `json:"greek"`
	Translations []string `json:"translations"`
	Section      string   `json:"section"`
}

type Query struct {
}

type ReadingSession struct {
	ID        string `json:"id"`
	UserID    string `json:"userId"`
	Author    string `json:"author"`
	Book      string `json:"book"`
	Reference string `json:"reference"`
	Section   string `json:"section"`
	CreatedAt string `json:"createdAt"`
}

type StartReadingInput struct {
	UserID    string  `json:"userId"`
	Author    string  `json:"author"`
	Book      string  `json:"book"`
	Reference *string `json:"reference,omitempty"`
	Section   *string `json:"section,omitempty"`
}

type Text struct {
	Author          string     `json:"author"`
	Book            string     `json:"book"`
	Type            string     `json:"type"`
	Reference       string     `json:"reference"`
	PerseusTextLink string     `json:"perseusTextLink"`
	Passages        []*Passage `json:"passages"`
}

type TextInput struct {
	Author    string  `json:"author"`
	Book      string  `json:"book"`
	Reference *string `json:"reference,omitempty"`
	Section   *string `json:"section,omitempty"`
}
