// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AnswerSection struct {
	Section               string `json:"section"`
	LevenshteinPercentage string `json:"levenshteinPercentage"`
	QuizSentence          string `json:"quizSentence"`
	AnswerSentence        string `json:"answerSentence"`
}

type CheckTextInput struct {
	Author       string                    `json:"author"`
	Book         string                    `json:"book"`
	Reference    string                    `json:"reference"`
	Translations []*TranslationAnswerInput `json:"translations"`
}

type CheckTextResult struct {
	AverageLevenshteinPercentage string           `json:"averageLevenshteinPercentage"`
	Sections                     []*AnswerSection `json:"sections"`
	PossibleTypos                []*Typo          `json:"possibleTypos"`
}

type CorpusAuthor struct {
	Name  string        `json:"name"`
	Books []*CorpusBook `json:"books"`
}

type CorpusBook struct {
	Name       string             `json:"name"`
	References []*CorpusReference `json:"references"`
}

type CorpusOptions struct {
	Authors []*CorpusAuthor `json:"authors"`
}

type CorpusReference struct {
	Name     string   `json:"name"`
	Sections []string `json:"sections"`
}

type Form struct {
	ID   string `json:"id"`
	Blob string `json:"blob"`
}

type Health struct {
	Healthy bool   `json:"healthy"`
	Time    string `json:"time"`
	Version string `json:"version"`
}

type Mutation struct {
}

type Passage struct {
	Greek        string   `json:"greek"`
	Translations []string `json:"translations"`
	Section      string   `json:"section"`
}

type Query struct {
}

type ReadingSession struct {
	ID           string `json:"id"`
	UserID       string `json:"userId"`
	FormID       string `json:"formId"`
	Form         *Form  `json:"form"`
	ProgressBlob string `json:"progressBlob"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type SaveProgressInput struct {
	ID           string `json:"id"`
	ProgressBlob string `json:"progressBlob"`
}

type StartReadingInput struct {
	UserID string `json:"userId"`
	FormID string `json:"formId"`
}

type Text struct {
	Author          string     `json:"author"`
	Book            string     `json:"book"`
	Type            string     `json:"type"`
	Reference       string     `json:"reference"`
	PerseusTextLink string     `json:"perseusTextLink"`
	Passages        []*Passage `json:"passages"`
}

type TextInput struct {
	Author    string  `json:"author"`
	Book      string  `json:"book"`
	Reference *string `json:"reference,omitempty"`
	Section   *string `json:"section,omitempty"`
}

type TranslationAnswerInput struct {
	Section     string `json:"section"`
	Translation string `json:"translation"`
}

type Typo struct {
	Source   string `json:"source"`
	Provided string `json:"provided"`
}
