FROM golang:1.26-alpine AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 go build -o /thoukydides .

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /thoukydides /thoukydides
ENTRYPOINT ["/thoukydides"]
