package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	diodorosv1 "github.com/odysseia-greek/ionia/diodoros/gen/go/v1"
	"github.com/odysseia-greek/ionia/herodotos/graph/model"
	thoukydidesv1 "github.com/odysseia-greek/ionia/thoukydides/gen/go/v1"
)

// CheckChapter is the resolver for the checkChapter field.
func (r *mutationResolver) CheckChapter(ctx context.Context, input model.CheckChapterInput) (*model.CheckChapterResult, error) {
	answers := make([]*thoukydidesv1.ChapterAnswer, 0, len(input.Answers))
	for _, answer := range input.Answers {
		answers = append(answers, &thoukydidesv1.ChapterAnswer{Text: answer.Text, LearnerText: answer.LearnerText})
	}
	response, err := r.Handler.CheckChapter(ctx, &thoukydidesv1.CheckChapterRequest{Chapter: input.Chapter, Answers: answers})
	if err != nil {
		return nil, err
	}
	result := &model.CheckChapterResult{Chapter: response.Chapter}
	for _, text := range response.Texts {
		result.Texts = append(result.Texts, &model.CheckedChapterText{Text: text.Text, SourceText: text.SourceText, ActualText: text.ActualText, LearnerText: text.LearnerText})
	}
	return result, nil
}

// CheckText is the resolver for the checkText field.
func (r *mutationResolver) CheckText(ctx context.Context, input model.CheckTextInput) (*model.CheckTextResult, error) {
	answers := make([]*diodorosv1.TranslationAnswer, 0, len(input.Translations))
	for _, answer := range input.Translations {
		answers = append(answers, &diodorosv1.TranslationAnswer{Section: answer.Section, Translation: answer.Translation})
	}
	response, err := r.Handler.CheckText(ctx, &diodorosv1.CheckTextRequest{Author: input.Author, Book: input.Book, Reference: input.Reference, Translations: answers})
	if err != nil {
		return nil, err
	}
	result := &model.CheckTextResult{AverageLevenshteinPercentage: response.AverageLevenshteinPercentage}
	for _, section := range response.Sections {
		result.Sections = append(result.Sections, &model.AnswerSection{Section: section.Section, LevenshteinPercentage: section.LevenshteinPercentage, QuizSentence: section.QuizSentence, AnswerSentence: section.AnswerSentence})
	}
	for _, typo := range response.PossibleTypos {
		result.PossibleTypos = append(result.PossibleTypos, &model.Typo{Source: typo.Source, Provided: typo.Provided})
	}
	return result, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	response, err := r.Handler.CoreHealth(ctx)
	if err != nil {
		return nil, err
	}
	return &model.Health{Healthy: response.Healthy, Time: response.Time, Version: response.Version}, nil
}

// CorpusHealth is the resolver for the corpusHealth field.
func (r *queryResolver) CorpusHealth(ctx context.Context) (*model.Health, error) {
	response, err := r.Handler.CorpusHealth(ctx)
	if err != nil {
		return nil, err
	}
	return &model.Health{Healthy: response.Healthy, Time: response.Time, Version: response.Version}, nil
}

// CorpusOptions is the resolver for the corpusOptions field.
func (r *queryResolver) CorpusOptions(ctx context.Context) (*model.CorpusOptions, error) {
	response, err := r.Handler.CorpusOptions(ctx)
	if err != nil {
		return nil, err
	}
	result := &model.CorpusOptions{}
	for _, author := range response.Authors {
		mappedAuthor := &model.CorpusAuthor{Name: author.Name}
		for _, book := range author.Books {
			mappedBook := &model.CorpusBook{Name: book.Name}
			for _, reference := range book.References {
				mappedBook.References = append(mappedBook.References, &model.CorpusReference{Name: reference.Name, Sections: reference.Sections})
			}
			mappedAuthor.Books = append(mappedAuthor.Books, mappedBook)
		}
		result.Authors = append(result.Authors, mappedAuthor)
	}
	return result, nil
}

// ChapterOptions is the resolver for the chapterOptions field.
func (r *queryResolver) ChapterOptions(ctx context.Context) (*model.ChapterOptions, error) {
	response, err := r.Handler.ChapterOptions(ctx)
	if err != nil {
		return nil, err
	}
	result := &model.ChapterOptions{}
	for _, chapter := range response.Chapters {
		result.Chapters = append(result.Chapters, &model.ChapterOption{Chapter: chapter.Chapter, Title: chapter.Title, Order: int(chapter.Order), Level: int(chapter.Level)})
	}
	return result, nil
}

// Chapter is the resolver for the chapter field.
func (r *queryResolver) Chapter(ctx context.Context, chapter string) (*model.Chapter, error) {
	response, err := r.Handler.GetChapter(ctx, &thoukydidesv1.GetChapterRequest{Chapter: chapter})
	if err != nil {
		return nil, err
	}
	result := &model.Chapter{
		Chapter: response.Chapter, Title: response.Title, Order: int(response.Order), Level: int(response.Level), Blob: response.Blob,
		Grammar:    make([]*model.Grammar, 0, len(response.Grammar)),
		Vocabulary: make([]*model.Vocabulary, 0, len(response.Vocabulary)),
		Texts:      make([]*model.ChapterText, 0, len(response.Texts)),
	}
	for _, grammar := range response.Grammar {
		item := &model.Grammar{Grammar: grammar.Grammar, Title: grammar.Title, Explanation: grammar.Explanation}
		if grammar.Example != nil {
			item.Example = &model.GrammarExample{Greek: grammar.Example.Greek, Translation: grammar.Example.Translation, Note: grammar.Example.Note}
		}
		result.Grammar = append(result.Grammar, item)
	}
	for _, vocabulary := range response.Vocabulary {
		result.Vocabulary = append(result.Vocabulary, &model.Vocabulary{Greek: vocabulary.Greek, Translation: vocabulary.Translation})
	}
	for _, text := range response.Texts {
		source := &model.ChapterTextSource{}
		if text.Source != nil {
			source = &model.ChapterTextSource{Author: text.Source.Author, Work: text.Source.Work, Reference: text.Source.Reference, Dialect: text.Source.Dialect}
		}
		result.Texts = append(result.Texts, &model.ChapterText{Text: text.Text, Title: text.Title, Type: text.Type, Source: source, Greek: text.Greek, ReadingHints: append([]string{}, text.ReadingHints...)})
	}
	return result, nil
}

// Text is the resolver for the text field.
func (r *queryResolver) Text(ctx context.Context, input model.TextInput) (*model.Text, error) {
	response, err := r.Handler.CreateText(ctx, &diodorosv1.CreateTextRequest{Author: input.Author, Book: input.Book, Reference: value(input.Reference), Section: value(input.Section)})
	if err != nil {
		return nil, err
	}
	passages := make([]*model.Passage, 0, len(response.Passages))
	for _, passage := range response.Passages {
		passages = append(passages, &model.Passage{Greek: passage.Greek, Translations: passage.Translations, Section: passage.Section})
	}
	return &model.Text{Author: response.Author, Book: response.Book, Type: response.Type, Reference: response.Reference, PerseusTextLink: response.PerseusTextLink, Passages: passages}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
