package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	diodorosv1 "github.com/odysseia-greek/ionia/diodoros/gen/go/v1"
	"github.com/odysseia-greek/ionia/herodotos/graph/model"
	thoukydidesv1 "github.com/odysseia-greek/ionia/thoukydides/gen/go/v1"
	"google.golang.org/protobuf/types/known/emptypb"
)

// StartReading is the resolver for the startReading field.
func (r *mutationResolver) StartReading(ctx context.Context, input model.StartReadingInput) (*model.ReadingSession, error) {
	response, err := r.Core.StartReading(ctx, &thoukydidesv1.StartReadingRequest{UserId: input.UserID, FormId: input.FormID})
	if err != nil {
		return nil, err
	}
	return reading(response), nil
}

// SaveProgress is the resolver for the saveProgress field.
func (r *mutationResolver) SaveProgress(ctx context.Context, input model.SaveProgressInput) (*model.ReadingSession, error) {
	response, err := r.Core.SaveProgress(ctx, &thoukydidesv1.SaveProgressRequest{Id: input.ID, ProgressBlob: input.ProgressBlob})
	if err != nil {
		return nil, err
	}
	return reading(response), nil
}

// CheckText is the resolver for the checkText field.
func (r *mutationResolver) CheckText(ctx context.Context, input model.CheckTextInput) (*model.CheckTextResult, error) {
	answers := make([]*diodorosv1.TranslationAnswer, 0, len(input.Translations))
	for _, answer := range input.Translations {
		answers = append(answers, &diodorosv1.TranslationAnswer{Section: answer.Section, Translation: answer.Translation})
	}
	response, err := r.Corpus.CheckText(ctx, &diodorosv1.CheckTextRequest{Author: input.Author, Book: input.Book, Reference: input.Reference, Translations: answers})
	if err != nil {
		return nil, err
	}
	result := &model.CheckTextResult{AverageLevenshteinPercentage: response.AverageLevenshteinPercentage}
	for _, section := range response.Sections {
		result.Sections = append(result.Sections, &model.AnswerSection{Section: section.Section, LevenshteinPercentage: section.LevenshteinPercentage, QuizSentence: section.QuizSentence, AnswerSentence: section.AnswerSentence})
	}
	for _, typo := range response.PossibleTypos {
		result.PossibleTypos = append(result.PossibleTypos, &model.Typo{Source: typo.Source, Provided: typo.Provided})
	}
	return result, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	response, err := r.Core.Health(ctx, &emptypb.Empty{})
	if err != nil {
		return nil, err
	}
	return &model.Health{Healthy: response.Healthy, Time: response.Time, Version: response.Version}, nil
}

// CorpusHealth is the resolver for the corpusHealth field.
func (r *queryResolver) CorpusHealth(ctx context.Context) (*model.Health, error) {
	response, err := r.Corpus.Health(ctx, &emptypb.Empty{})
	if err != nil {
		return nil, err
	}
	return &model.Health{Healthy: response.Healthy, Time: response.Time, Version: response.Version}, nil
}

// CorpusOptions is the resolver for the corpusOptions field.
func (r *queryResolver) CorpusOptions(ctx context.Context) (*model.CorpusOptions, error) {
	response, err := r.Corpus.Options(ctx, &emptypb.Empty{})
	if err != nil {
		return nil, err
	}
	result := &model.CorpusOptions{}
	for _, author := range response.Authors {
		mappedAuthor := &model.CorpusAuthor{Name: author.Name}
		for _, book := range author.Books {
			mappedBook := &model.CorpusBook{Name: book.Name}
			for _, reference := range book.References {
				mappedBook.References = append(mappedBook.References, &model.CorpusReference{Name: reference.Name, Sections: reference.Sections})
			}
			mappedAuthor.Books = append(mappedAuthor.Books, mappedBook)
		}
		result.Authors = append(result.Authors, mappedAuthor)
	}
	return result, nil
}

// Forms is the resolver for the forms field.
func (r *queryResolver) Forms(ctx context.Context, size *int) ([]*model.Form, error) {
	amount := int32(20)
	if size != nil {
		amount = int32(*size)
	}
	response, err := r.Core.ListForms(ctx, &thoukydidesv1.ListFormsRequest{Size: amount})
	if err != nil {
		return nil, err
	}
	forms := make([]*model.Form, 0, len(response.Forms))
	for _, form := range response.Forms {
		forms = append(forms, &model.Form{ID: form.Id, Blob: form.Blob})
	}
	return forms, nil
}

// Form is the resolver for the form field.
func (r *queryResolver) Form(ctx context.Context, id string) (*model.Form, error) {
	form, err := r.Core.GetForm(ctx, &thoukydidesv1.GetFormRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return &model.Form{ID: form.Id, Blob: form.Blob}, nil
}

// Text is the resolver for the text field.
func (r *queryResolver) Text(ctx context.Context, input model.TextInput) (*model.Text, error) {
	response, err := r.Corpus.CreateText(ctx, &diodorosv1.CreateTextRequest{Author: input.Author, Book: input.Book, Reference: value(input.Reference), Section: value(input.Section)})
	if err != nil {
		return nil, err
	}
	passages := make([]*model.Passage, 0, len(response.Passages))
	for _, passage := range response.Passages {
		passages = append(passages, &model.Passage{Greek: passage.Greek, Translations: passage.Translations, Section: passage.Section})
	}
	return &model.Text{Author: response.Author, Book: response.Book, Type: response.Type, Reference: response.Reference, PerseusTextLink: response.PerseusTextLink, Passages: passages}, nil
}

// Reading is the resolver for the reading field.
func (r *queryResolver) Reading(ctx context.Context, id string) (*model.ReadingSession, error) {
	response, err := r.Core.GetReading(ctx, &thoukydidesv1.GetReadingRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return reading(response), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
